In [2]:
import numpy as np
from scipy import linalg
from scipy.optimize import minimize

In [3]:
#                 (0,244)--------(294,244)
#                     |               |
# Polygone ->         |               |
#                     |               |
#                   (0,0)--------(294, 0)

Zhang’s Calibration DLT METHOD

In [133]:
pol1 = (582/1280, 271/720)
pol1_2 = (486/1280, 384/720)
pol2 = (371/1280, 520/720)
pol2_2 = (614/1280, 601/720)
pol3 = (945/1280, 710/720)
pol3_2 = (976/1280, 471/720)
pol4 = (994/1280, 317/720)
pol4_2 = (764/1280, 290/720)


x_res, y_res = (1920, 1080)# resolution
polygon = np.array([(pol1[0] * x_res, pol1[1] * y_res), 
                    (pol1_2[0] * x_res, pol1_2[1] * y_res), 
                    (pol2[0] * x_res, pol2[1] * y_res),
                    (pol2_2[0] * x_res, pol2_2[1] * y_res),
                    (pol3[0] * x_res, pol3[1] * y_res),
                    (pol3_2[0] * x_res, pol3_2[1] * y_res),
                    (pol4[0] * x_res, pol4[1] * y_res), 
                    (pol4_2[0] * x_res, pol4_2[1] * y_res)], dtype=int)#points for polygone in the center

def dlt(pt):
    
    pointsW = [(0, 244), (0,122), (0, 0), (147, 0), (294, 0), (294, 122), (294, 244), (147, 244)]
    pointsPX = polygon
    print(pointsW, '\n', pointsPX)

    if len(pointsPX) != len(pointsW): return

    A = np.zeros((len(pointsW)*2, 9))
    for k, W, PX in zip(range(0, len(pointsW)*2, 2),pointsW, pointsPX):
        xw = W[0]
        yw = W[1]

        u = PX[0]
        v = PX[1]

        A[k] = [-xw, -yw, -1, 0, 0, 0, u*xw, u*yw, u]
        A[k+1] = [0, 0, 0, -xw, -yw, -1, v*xw, v*yw, v]
    
    U,D,V = np.linalg.svd(A)
    m_ext = np.reshape(V[-1] / V[-1][-1], (3,3))
    vector = np.array([pt[0], pt[1], 1])
    print(m_ext)
    #BACKWARD PIXEL -> WORLD
    result = np.linalg.solve(m_ext, vector)
    result = result / result[-1]
    print(result[:2])

    #FORWARD WORLD -> PIXEL
    # result = np.dot(m_ext, vector)
    # result = result / result[-1]
    # print(result)

dlt([873, 406])

[(0, 244), (0, 122), (0, 0), (147, 0), (294, 0), (294, 122), (294, 244), (147, 244)] 
 [[ 873  406]
 [ 729  576]
 [ 556  780]
 [ 921  901]
 [1417 1065]
 [1464  706]
 [1491  475]
 [1146  435]]
[[ 1.51531153e+00  2.72585975e+00  5.56845287e+02]
 [-1.35147868e-01 -8.90424868e-01  7.89882949e+02]
 [-9.95718814e-04  1.67466324e-03  1.00000000e+00]]
[  2.76354815 244.93238028]
